[package]
name = "bible-bot-rust"
version = "0.1.0"
authors = ["Joel Clarke <joel.clarke273@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
orca = "0.7.0"
regex = "1.2.1"
reqwest = "0.9.19"
rust-s3 = "0.15.0"
serde = "1.0.99"
serde_json = "1.0.40"
toml = "0.5.3"